### ISSUE TITLE
Incompatible with Netbeans 7.2, 7.3

### ISSUE THREAD

**Issue by JamesSwift** [lomadurov/netbeans-jslint#3]
Any chance of this plugin being updated for netbeans 7.3? I'm really missing it.

**Comment by MarkMurphy** [comment]
+1 Would really like this to work in 7.3

**Comment by johannes-weber** [comment]
+1 for a working plugin in 7.3

**Comment by Jaxolotl** [comment]
+1 for a  7.3 compatible version, I'm really missing it too!!!!

**Comment by semi-sentient** [comment]
I would love to see this added as well. JSLint is a valuable resource and not having it for the latest versions of NetBeans is giving me thoughts of switching to another IDE.

**Comment by lomadurov** [comment]
Unfortunately, I moved to WebStorm and I no longer able to support this plugin.

**Comment by lomadurov** [comment]
Im update plugin for NetBeans 7.3
